version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: excon
    versions:
    - 0.78.1
    - 0.79.0
  - dependency-name: sendgrid-ruby
    versions:
    - 6.3.9
  - dependency-name: loofah
    versions:
    - 2.9.0
