---
development:
  cloud_name: minerva-webapp
  api_key: '697337731636442'
  api_secret: zQ89HtOEbWv5rTnEwagqNvvWRek
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: minerva-webapp
  api_key: '697337731636442'
  api_secret: zQ89HtOEbWv5rTnEwagqNvvWRek
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: minerva-webapp
  api_key: '697337731636442'
  api_secret: zQ89HtOEbWv5rTnEwagqNvvWRek
  enhance_image_tag: true
  static_image_support: false
